'use client'

import { useState } from 'react'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Badge } from '@/components/ui/badge'
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from '@/components/ui/dialog'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { Label } from '@/components/ui/label'
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group'
import {
  Plus,
  Pencil,
  Trash2,
  Calendar,
  Star,
  ChevronLeft,
  ChevronRight,
  Sparkles,
} from 'lucide-react'
import type { MidTermPlan, TextbookRange, WeeklyTask, DistributionMethod, StudyBook } from '@/lib/types'
import { cn } from '@/lib/utils'

interface PlanScreenProps {
  books: StudyBook[]
  weeklyTasks: WeeklyTask[]
  onAddWeeklyTask: (task: Omit<WeeklyTask, 'id'>) => void
  onUpdateWeeklyTask?: (taskId: string, updatedData: Partial<WeeklyTask>) => void
  onDeleteWeeklyTask?: (taskId: string) => void
}

const POINTS_PER_PAGE = 5

export function PlanScreen({ books, weeklyTasks, onAddWeeklyTask, onUpdateWeeklyTask, onDeleteWeeklyTask }: PlanScreenProps) {
  const [activeSubTab, setActiveSubTab] = useState<'midterm' | 'weekly'>('midterm')

  // Mid-term plan state
  const [midTermPlan, setMidTermPlan] = useState<MidTermPlan>({
    id: 'plan-1',
    name: '',
    startDate: '',
    endDate: '',
    textbookRanges: [],
  })
  const [showAddTextbookDialog, setShowAddTextbookDialog] = useState(false)
  const [editingRangeId, setEditingRangeId] = useState<string | null>(null)
  const [textbookForm, setTextbookForm] = useState({
    bookId: '',
    startPage: '',
    endPage: '',
  })

  // Weekly plan state
  const [currentWeek, setCurrentWeek] = useState(1)
  const [showAddTaskDialog, setShowAddTaskDialog] = useState(false)
  const [editingTaskId, setEditingTaskId] = useState<string | null>(null)
  const [taskForm, setTaskForm] = useState({
    bookId: '',
    startPage: '',
    endPage: '',
  })
  const [showAutoGenerateDialog, setShowAutoGenerateDialog] = useState(false)
  const [distributionMethod, setDistributionMethod] = useState<DistributionMethod>('even')

  // Calculate week dates
  const getWeekDates = (weekNum: number) => {
    const baseDate = new Date(2026, 2, 16) // Mar 16
    const start = new Date(baseDate)
    start.setDate(start.getDate() + (weekNum - 1) * 7)
    const end = new Date(start)
    end.setDate(end.getDate() + 6)
    const formatDate = (d: Date) => `${d.toLocaleDateString('en-US', { month: 'short' })} ${d.getDate()}`
    return `${formatDate(start)} - ${formatDate(end)}`
  }

  const totalPlannedPoints = weeklyTasks.reduce((sum, task) => sum + task.points, 0)

  // Handlers for mid-term plan
  const handleAddTextbookRange = () => {
    const book = books.find((b) => b.id === textbookForm.bookId)
    if (!book) return

    const newRange: TextbookRange = {
      id: editingRangeId || `range-${Date.now()}`,
      bookId: textbookForm.bookId,
      bookName: book.name,
      subject: book.subject,
      startPage: parseInt(textbookForm.startPage),
      endPage: parseInt(textbookForm.endPage),
    }

    if (editingRangeId) {
      setMidTermPlan((prev) => ({
        ...prev,
        textbookRanges: prev.textbookRanges.map((r) =>
          r.id === editingRangeId ? newRange : r
        ),
      }))
    } else {
      setMidTermPlan((prev) => ({
        ...prev,
        textbookRanges: [...prev.textbookRanges, newRange],
      }))
    }

    setTextbookForm({ bookId: '', startPage: '', endPage: '' })
    setEditingRangeId(null)
    setShowAddTextbookDialog(false)
  }

  const handleEditRange = (range: TextbookRange) => {
    setTextbookForm({
      bookId: range.bookId,
      startPage: range.startPage.toString(),
      endPage: range.endPage.toString(),
    })
    setEditingRangeId(range.id)
    setShowAddTextbookDialog(true)
  }

  const handleDeleteRange = (rangeId: string) => {
    setMidTermPlan((prev) => ({
      ...prev,
      textbookRanges: prev.textbookRanges.filter((r) => r.id !== rangeId),
    }))
  }

  // Handlers for weekly plan
  const handleAddWeeklyTask = () => {
  if (!taskForm.bookId || !taskForm.startPage || !taskForm.endPage) return

  const startPage = Number(taskForm.startPage)
  const endPage = Number(taskForm.endPage)

  const selectedBook = books.find((b) => b.id === taskForm.bookId)

  const updates = {
    weekId: `week-${currentWeek}`,
    bookId: taskForm.bookId,
    bookName: selectedBook?.name ?? "",
    startPage,
    endPage,
    points: (endPage - startPage) * POINTS_PER_PAGE,
  }

  if (editingTaskId) {
    onUpdateWeeklyTask?.(editingTaskId, updates)
  } else {
    onAddWeeklyTask?.(updates)
  }

  setShowAddTaskDialog(false)
  setTaskForm({ bookId: "", startPage: "", endPage: "" })
  setEditingTaskId(null)
}

  const handleEditWeeklyTask = (task: WeeklyTask) => {
  setTaskForm({
    bookId: task.bookId,
    startPage: task.startPage.toString(),
    endPage: task.endPage.toString(),
  })

  setEditingTaskId(task.id)
  setShowAddTaskDialog(true)
}

  const handleDeleteWeeklyTask = (taskId: string) => {
    onDeleteWeeklyTask?.(taskId)
  }

  const generateDailyPreview = () => {
    if (weeklyTasks.length === 0) return []
    const task = weeklyTasks[0]
    const totalPages = task.endPage - task.startPage
    const pagesPerDay = Math.ceil(totalPages / 6)
    const days = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat']
    
    return days.map((day, i) => {
      const start = task.startPage + i * pagesPerDay
      const end = Math.min(start + pagesPerDay - 1, task.endPage)
      return `${day} p${start}–${end}`
    })
  }

  const filteredTasks = weeklyTasks.filter((task) => task.weekId === `week-${currentWeek}`)

  return (
    <div className="flex flex-col gap-4 pb-24">
      {/* Header */}
      <div className="flex flex-col gap-4">
        <h1 className="text-2xl font-bold text-foreground">Plan</h1>

        {/* Sub-tab switcher */}
        <div className="flex rounded-lg bg-muted p-1">
          <button
            onClick={() => setActiveSubTab('midterm')}
            className={cn(
              'flex-1 rounded-md px-4 py-2 text-sm font-medium transition-colors',
              activeSubTab === 'midterm'
                ? 'bg-card text-foreground shadow-sm'
                : 'text-muted-foreground hover:text-foreground'
            )}
          >
            Mid-term Plan
          </button>
          <button
            onClick={() => setActiveSubTab('weekly')}
            className={cn(
              'flex-1 rounded-md px-4 py-2 text-sm font-medium transition-colors',
              activeSubTab === 'weekly'
                ? 'bg-card text-foreground shadow-sm'
                : 'text-muted-foreground hover:text-foreground'
            )}
          >
            Weekly Plan
          </button>
        </div>
      </div>

      {/* Mid-term Plan Tab */}
      {activeSubTab === 'midterm' && (
        <div className="flex flex-col gap-4">
          {/* Plan Information Card */}
          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="text-base">Plan Information</CardTitle>
            </CardHeader>
            <CardContent className="flex flex-col gap-4">
              <div className="flex flex-col gap-2">
                <Label htmlFor="plan-name" className="text-sm text-muted-foreground">
                  Plan name
                </Label>
                <Input
                  id="plan-name"
                  placeholder="e.g., April Study Plan"
                  value={midTermPlan.name}
                  onChange={(e) =>
                    setMidTermPlan((prev) => ({ ...prev, name: e.target.value }))
                  }
                />
              </div>
              <div className="grid grid-cols-2 gap-3">
                <div className="flex flex-col gap-2">
                  <Label htmlFor="start-date" className="text-sm text-muted-foreground">
                    Start date
                  </Label>
                  <div className="relative">
                    <Input
                      id="start-date"
                      type="date"
                      value={midTermPlan.startDate}
                      onChange={(e) =>
                        setMidTermPlan((prev) => ({ ...prev, startDate: e.target.value }))
                      }
                      className="pl-9"
                    />
                    <Calendar className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
                  </div>
                </div>
                <div className="flex flex-col gap-2">
                  <Label htmlFor="end-date" className="text-sm text-muted-foreground">
                    End date
                  </Label>
                  <div className="relative">
                    <Input
                      id="end-date"
                      type="date"
                      value={midTermPlan.endDate}
                      onChange={(e) =>
                        setMidTermPlan((prev) => ({ ...prev, endDate: e.target.value }))
                      }
                      className="pl-9"
                    />
                    <Calendar className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Textbook Ranges */}
          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="text-base">Textbook Ranges</CardTitle>
            </CardHeader>
            <CardContent className="flex flex-col gap-3">
              {midTermPlan.textbookRanges.length === 0 ? (
                <p className="py-4 text-center text-sm text-muted-foreground">
                  No textbooks added yet
                </p>
              ) : (
                midTermPlan.textbookRanges.map((range) => (
                  <Card key={range.id} className="border-border/50">
                    <CardContent className="flex items-start justify-between p-4">
                      <div className="flex flex-col gap-1">
                        <span className="font-medium text-foreground">
                          {range.bookName}
                        </span>
                        <Badge variant="secondary" className="w-fit text-xs">
                          {range.subject}
                        </Badge>
                        <div className="mt-2 flex flex-col text-sm text-muted-foreground">
                          <span>Start page: {range.startPage}</span>
                          <span>End page: {range.endPage}</span>
                        </div>
                      </div>
                      <div className="flex gap-1">
                        <Button
                          variant="ghost"
                          size="icon"
                          className="h-8 w-8"
                          onClick={() => handleEditRange(range)}
                        >
                          <Pencil className="h-4 w-4" />
                        </Button>
                        <Button
                          variant="ghost"
                          size="icon"
                          className="h-8 w-8 text-destructive hover:text-destructive"
                          onClick={() => handleDeleteRange(range.id)}
                        >
                          <Trash2 className="h-4 w-4" />
                        </Button>
                      </div>
                    </CardContent>
                  </Card>
                ))
              )}

              <Button
                variant="outline"
                className="mt-2 w-full border-dashed"
                onClick={() => setShowAddTextbookDialog(true)}
              >
                <Plus className="mr-2 h-4 w-4" />
                Add Textbook
              </Button>
            </CardContent>
          </Card>

          {/* Save Button */}
          <Button className="w-full" size="lg">
            Save Plan
          </Button>
        </div>
      )}

      {/* Weekly Plan Tab */}
      {activeSubTab === 'weekly' && (
        <div className="flex flex-col gap-4">
          {/* Week Header */}
          <Card>
            <CardContent className="flex flex-col gap-3 p-4">
              <div className="flex items-center justify-between">
                <Button
                  variant="ghost"
                  size="icon"
                  className="h-8 w-8"
                  onClick={() => setCurrentWeek((w) => Math.max(1, w - 1))}
                >
                  <ChevronLeft className="h-5 w-5" />
                </Button>
                <div className="flex flex-col items-center">
                  <span className="text-lg font-semibold">Week {currentWeek}</span>
                  <span className="text-sm text-muted-foreground">
                    {getWeekDates(currentWeek)}
                  </span>
                </div>
                <Button
                  variant="ghost"
                  size="icon"
                  className="h-8 w-8"
                  onClick={() => setCurrentWeek((w) => w + 1)}
                >
                  <ChevronRight className="h-5 w-5" />
                </Button>
              </div>
              <div className="flex items-center justify-center gap-2 rounded-lg bg-warning/10 px-4 py-2">
                <Star className="h-5 w-5 text-warning" />
                <span className="font-medium text-warning-foreground">
                  Total Planned Points: {totalPlannedPoints}
                </span>
              </div>
            </CardContent>
          </Card>

          {/* Weekly Tasks */}
          <div className="flex flex-col gap-3">
            <h2 className="text-sm font-medium text-muted-foreground">Study Tasks</h2>
            {weeklyTasks.length === 0 ? (
              <Card>
                <CardContent className="py-8 text-center text-sm text-muted-foreground">
                  No tasks added yet
                </CardContent>
              </Card>
            ) : (
              filteredTasks.map((task) => {
                const pageCount = task.endPage - task.startPage
                return (
                  <Card key={task.id}>
                    <CardContent className="flex items-center justify-between p-4">
                      <div className="flex flex-col gap-1">
                        <span className="font-medium text-foreground">
                          {task.bookName}
                        </span>
                        <div className="flex items-center gap-3 text-sm text-muted-foreground">
                          <span>
                            p{task.startPage} → p{task.endPage}
                          </span>
                          <span className="text-xs">{pageCount} pages</span>
                        </div>
                        <div className="mt-1 flex items-center gap-1 text-sm font-medium text-primary">
                          <Star className="h-4 w-4" />
                          {task.points} pts
                        </div>
                      </div>
                      <div className="flex gap-1">
                        <Button
                          variant="ghost"
                          size="icon"
                          className="h-8 w-8"
                          onClick={() => handleEditWeeklyTask(task)}
                        >
                          <Pencil className="h-4 w-4" />
                        </Button>
                        <Button
                          variant="ghost"
                          size="icon"
                          className="h-8 w-8 text-destructive hover:text-destructive"
                          onClick={() => {
                            if (confirm("このタスクを削除しますか？")) {
                              handleDeleteWeeklyTask(task.id)
                            }
                          }}
                        >
                          <Trash2 className="h-4 w-4" />
                        </Button>
                      </div>
                    </CardContent>
                  </Card>
                )
              })
            )}

            <Button
              variant="outline"
              className="w-full border-dashed"
              onClick={() => setShowAddTaskDialog(true)}
            >
              <Plus className="mr-2 h-4 w-4" />
              Add Study Task
            </Button>
          </div>

          {/* Auto Generate Button */}
          <Button
            className="w-full"
            size="lg"
            onClick={() => setShowAutoGenerateDialog(true)}
          >
            <Sparkles className="mr-2 h-4 w-4" />
            Auto Generate Daily Tasks
          </Button>
        </div>
      )}

      {/* Add Textbook Dialog */}
      <Dialog open={showAddTextbookDialog} onOpenChange={setShowAddTextbookDialog}>
        <DialogContent className="max-w-[340px] rounded-xl">
          <DialogHeader>
            <DialogTitle>
              {editingRangeId ? 'Edit Textbook' : 'Add Textbook'}
            </DialogTitle>
          </DialogHeader>
          <div className="flex flex-col gap-4 py-4">
            <div className="flex flex-col gap-2">
              <Label>Select textbook</Label>
              <Select
                value={textbookForm.bookId}
                onValueChange={(v) => setTextbookForm((prev) => ({ ...prev, bookId: v }))}
              >
                <SelectTrigger>
                  <SelectValue placeholder="Choose a textbook" />
                </SelectTrigger>
                <SelectContent>
                  {books.map((book) => (
                    <SelectItem key={book.id} value={book.id}>
                      {book.name} ({book.subject})
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div className="grid grid-cols-2 gap-3">
              <div className="flex flex-col gap-2">
                <Label>Start page</Label>
                <Input
                  type="number"
                  value={textbookForm.startPage}
                  onChange={(e) =>
                    setTextbookForm((prev) => ({ ...prev, startPage: e.target.value }))
                  }
                  placeholder="1"
                />
              </div>
              <div className="flex flex-col gap-2">
                <Label>End page</Label>
                <Input
                  type="number"
                  value={textbookForm.endPage}
                  onChange={(e) =>
                    setTextbookForm((prev) => ({ ...prev, endPage: e.target.value }))
                  }
                  placeholder="200"
                />
              </div>
            </div>
          </div>
          <DialogFooter className="flex-row gap-2">
            <Button
              variant="outline"
              className="flex-1"
              onClick={() => {
                setShowAddTextbookDialog(false)
                setTextbookForm({ bookId: '', startPage: '', endPage: '' })
                setEditingRangeId(null)
              }}
            >
              Cancel
            </Button>
            <Button
              className="flex-1"
              onClick={handleAddTextbookRange}
              disabled={!textbookForm.bookId || !textbookForm.startPage || !textbookForm.endPage}
            >
              {editingRangeId ? 'Update' : 'Add'}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Add Task Dialog */}
      <Dialog open={showAddTaskDialog} onOpenChange={setShowAddTaskDialog}>
        <DialogContent className="max-w-[340px] rounded-xl">
          <DialogHeader>
            <DialogTitle>
              {editingTaskId ? 'Edit Study Task' : 'Add Study Task'}
            </DialogTitle>
          </DialogHeader>
          <div className="flex flex-col gap-4 py-4">
            <div className="flex flex-col gap-2">
              <Label>Select textbook</Label>
              <Select
                value={taskForm.bookId}
                onValueChange={(v) => setTaskForm((prev) => ({ ...prev, bookId: v }))}
              >
                <SelectTrigger>
                  <SelectValue placeholder="Choose a textbook" />
                </SelectTrigger>
                <SelectContent>
                  {books.map((book) => (
                    <SelectItem key={book.id} value={book.id}>
                      {book.name}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div className="grid grid-cols-2 gap-3">
              <div className="flex flex-col gap-2">
                <Label>Start page</Label>
                <Input
                  type="number"
                  value={taskForm.startPage}
                  onChange={(e) =>
                    setTaskForm((prev) => ({ ...prev, startPage: e.target.value }))
                  }
                  placeholder="30"
                />
              </div>
              <div className="flex flex-col gap-2">
                <Label>End page</Label>
                <Input
                  type="number"
                  value={taskForm.endPage}
                  onChange={(e) =>
                    setTaskForm((prev) => ({ ...prev, endPage: e.target.value }))
                  }
                  placeholder="60"
                />
              </div>
            </div>
            {taskForm.startPage && taskForm.endPage && (
              <div className="rounded-lg bg-muted p-3 text-center">
                <span className="text-sm text-muted-foreground">
                  {parseInt(taskForm.endPage) - parseInt(taskForm.startPage)} pages ={' '}
                </span>
                <span className="font-medium text-primary">
                  {(parseInt(taskForm.endPage) - parseInt(taskForm.startPage)) * POINTS_PER_PAGE} pts
                </span>
              </div>
            )}
          </div>
          <DialogFooter className="flex-row gap-2">
            <Button
              variant="outline"
              className="flex-1"
              onClick={() => {
                setShowAddTaskDialog(false)
                setTaskForm({ bookId: '', startPage: '', endPage: '' })
                setEditingTaskId(null)
              }}
            >
              Cancel
            </Button>
            <Button
              className="flex-1"
              onClick={handleAddWeeklyTask}
              disabled={!taskForm.bookId || !taskForm.startPage || !taskForm.endPage}
            >
              {editingTaskId ? 'Update' : 'Add'}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Auto Generate Dialog */}
      <Dialog open={showAutoGenerateDialog} onOpenChange={setShowAutoGenerateDialog}>
        <DialogContent className="max-w-[340px] rounded-xl">
          <DialogHeader>
            <DialogTitle>Generate Daily Tasks</DialogTitle>
          </DialogHeader>
          <div className="flex flex-col gap-4 py-4">
            <div className="flex flex-col gap-2">
              <Label>Distribution method</Label>
              <RadioGroup
                value={distributionMethod}
                onValueChange={(v) => setDistributionMethod(v as DistributionMethod)}
                className="flex flex-col gap-3"
              >
                <div className="flex items-center space-x-3">
                  <RadioGroupItem value="even" id="even" />
                  <Label htmlFor="even" className="font-normal">
                    Even distribution
                  </Label>
                </div>
                <div className="flex items-center space-x-3">
                  <RadioGroupItem value="study-time" id="study-time" />
                  <Label htmlFor="study-time" className="font-normal">
                    Study-time based
                  </Label>
                </div>
                <div className="flex items-center space-x-3">
                  <RadioGroupItem value="custom" id="custom" />
                  <Label htmlFor="custom" className="font-normal">
                    Custom weekday ratio
                  </Label>
                </div>
              </RadioGroup>
            </div>

            {weeklyTasks.length > 0 && (
              <div className="flex flex-col gap-2">
                <Label className="text-muted-foreground">Preview</Label>
                <div className="rounded-lg bg-muted p-3">
                  <div className="flex flex-col gap-1 text-sm font-mono">
                    {generateDailyPreview().map((line, i) => (
                      <span key={i}>{line}</span>
                    ))}
                  </div>
                </div>
              </div>
            )}
          </div>
          <DialogFooter className="flex-row gap-2">
            <Button
              variant="outline"
              className="flex-1"
              onClick={() => setShowAutoGenerateDialog(false)}
            >
              Cancel
            </Button>
            <Button
              className="flex-1"
              onClick={() => {
                // In a real app, this would generate daily tasks
                setShowAutoGenerateDialog(false)
              }}
            >
              Generate
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  )
}
