'use client'

import { useState } from 'react'
import { Card, CardContent} from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
  DialogTrigger
} from '@/components/ui/dialog'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { Label } from '@/components/ui/label'
import {
  Plus,
  Minus,
  Pencil,
  Trash2,
  ChevronLeft,
  ChevronRight,
  Sparkles,
} from 'lucide-react'
import type { WeeklyTask, StudyBook, Priority } from '@/lib/types'
import { Fascinate_Inline } from 'next/font/google'
import { PriorityBadge } from '../priority-badge'

interface PlanScreenProps {
  books: StudyBook[]
  weeklyTasks: WeeklyTask[]
  onAddWeeklyTask: (task: Omit<WeeklyTask, 'id'>) => void
  onUpdateWeeklyTask?: (taskId: string, updatedData: Partial<WeeklyTask>) => void
  onDeleteWeeklyTask?: (taskId: string) => void
  onGenerateDailyTasks?: (task: WeeklyTask, date: Date[], weights: number[]) => void
}

export function PlanScreen({ books, weeklyTasks, onAddWeeklyTask, onUpdateWeeklyTask, onDeleteWeeklyTask, onGenerateDailyTasks }: PlanScreenProps) {
  const [currentWeek, setCurrentWeek] = useState(getWeekNumber(new Date(2026,3,6), new Date()))
  const [showAddTaskDialog, setShowAddTaskDialog] = useState(false)
  const [editingTaskId, setEditingTaskId] = useState<string | null>(null)
  const [taskForm, setTaskForm] = useState({
    bookId: '',
    startPage: '',
    endPage: '',
    priority: '',
  })
  const [showAutoGenerateDialog, setShowAutoGenerateDialog] = useState(false)
  const [selectedTask, setSelectedTask] = useState<WeeklyTask | null>(null)
  const [selectedSubject, setSelectedSubject] = useState("all");
  const [weights, setWeights] = useState<number[]>([
    1, 1, 1, 1, 1, 3, 3
  ])
  const WEEKDAYS = [
    "Mon",
    "Tue",
    "Wed",
    "Thu",
    "Fri",
    "Sat",
    "Sun"
  ]

  function getWeekNumber(startDateCounter: Date, targetDate: Date = new Date()): number {
    console.log(new Date())
    // 1日のミリ秒数 (1000ms * 60s * 60m * 24h)
    const MS_PER_DAY = 86400000;

    // 時刻の影響を排除するため、両方の日の「00:00:00」のタイムスタンプを取得
    const start = new Date(
      startDateCounter.getFullYear(),
      startDateCounter.getMonth(),
      startDateCounter.getDate()
    ).getTime();

    const target = new Date(
      targetDate.getFullYear(),
      targetDate.getMonth(),
      targetDate.getDate()
    ).getTime();

    // 経過日数を計算
    const diffInDays = Math.floor((target - start) / MS_PER_DAY);

    // 0〜6日経過 = 1週目、7〜13日経過 = 2週目...
    // もし開始日より前の日付が指定された場合はマイナスの週数、または0を返す
    return Math.floor(diffInDays / 7) + 1;
  }

  // Calculate week dates
  const getWeekDates = (weekNum: number) => {
    const baseDate = new Date(2026, 3, 6) // Mar 16
    const start = new Date(baseDate)
    start.setDate(start.getDate() + (weekNum - 1) * 7)
    const end = new Date(start)
    end.setDate(end.getDate() + 6)
    const formatDate = (d: Date) => `${d.toLocaleDateString('en-US', { month: 'short' })} ${d.getDate()}`
    return `${formatDate(start)} - ${formatDate(end)}`
  }

  // Handlers for weekly plan
  const handleAddWeeklyTask = () => {
    if (!taskForm.bookId || !taskForm.startPage || !taskForm.endPage) return

    const startPage = Number(taskForm.startPage)
    const endPage = Number(taskForm.endPage)

    const selectedBook = books.find((b) => b.id === taskForm.bookId)

    const updates = {
      weekId: `week-${currentWeek}`,
      bookId: taskForm.bookId,
      bookName: selectedBook?.name ?? "",
      startPage,
      endPage,
      priority: taskForm.priority as Priority,
      subject: selectedBook?.subject ?? "",
      isDistributed: false
    }

    if (editingTaskId) {
      onUpdateWeeklyTask?.(editingTaskId, updates)
    } else {
      onAddWeeklyTask?.(updates)
    }

    setShowAddTaskDialog(false)
    setTaskForm({ bookId: "", startPage: "", endPage: "" , priority: ""})
    setEditingTaskId(null)
  }

  const handleEditWeeklyTask = (task: WeeklyTask) => {
    setTaskForm({
      bookId: task.bookId,
      startPage: task.startPage.toString(),
      endPage: task.endPage.toString(),
      priority: task.priority,
    })

    setEditingTaskId(task.id)
    setShowAddTaskDialog(true)
  }

  const handleDeleteWeeklyTask = (taskId: string) => {
    onDeleteWeeklyTask?.(taskId)
  }

  const handleGenerateDailyTasks = (task: WeeklyTask) => {
    if (!task.isDistributed) {
      const baseDate = new Date(2026, 3, 6)

      const start = new Date(baseDate)
      start.setDate(start.getDate() + (currentWeek - 1) * 7)

      const days: Date[] = []

      for (let i = 0; i < 7; i++) {
        const day = new Date(start)
        day.setDate(start.getDate() + i)
        days.push(day)
      }

      onGenerateDailyTasks?.(task, days, weights)
    }
    setShowAutoGenerateDialog(false)
  }

  const filteredTasks = weeklyTasks.filter((task) => task.weekId === `week-${currentWeek}`)

  const filteredBooks =
  selectedSubject === "all"
    ? books
    : books.filter((book) => book.subject === selectedSubject);

  return (
    <div className="flex flex-col gap-4 pb-24">
      {/* Header */}
      <div className="flex flex-col gap-4">
        <h1 className="text-2xl font-bold text-foreground">Plan</h1>
      </div>

        <div className="flex flex-col gap-4">
          {/* Week Header */}
          <Card>
            <CardContent className="flex flex-col gap-3 p-4">
              <div className="flex items-center justify-between">
                <Button
                  variant="ghost"
                  size="icon"
                  className="h-8 w-8"
                  onClick={() => setCurrentWeek((w) => Math.max(1, w - 1))}
                >
                  <ChevronLeft className="h-5 w-5" />
                </Button>
                <div className="flex flex-col items-center">
                  <span className="text-lg font-semibold">Week {currentWeek}</span>
                  <span className="text-sm text-muted-foreground">
                    {getWeekDates(currentWeek)}
                  </span>
                </div>
                <Button
                  variant="ghost"
                  size="icon"
                  className="h-8 w-8"
                  onClick={() => setCurrentWeek((w) => w + 1)}
                >
                  <ChevronRight className="h-5 w-5" />
                </Button>
              </div>
            </CardContent>
          </Card>

          {/* Weekly Tasks */}
          <div className="flex flex-col gap-3">
            <h2 className="text-sm font-medium text-muted-foreground">Study Tasks</h2>
            {weeklyTasks.length === 0 ? (
              <Card>
                <CardContent className="py-8 text-center text-sm text-muted-foreground">
                  No tasks added yet
                </CardContent>
              </Card>
            ) : (
              filteredTasks.map((task) => {
                const pageCount = task.endPage - task.startPage + 1
                return (
                  <Card key={task.id}>
                    <CardContent className="flex items-center justify-between p-4">
                      <div className="flex flex-col gap-1">
                        <span className="font-medium text-foreground">
                          {task.bookName}
                        </span>
                        <div className="flex items-center gap-3 text-sm text-muted-foreground mt-1">
                          <span>
                            p{task.startPage} → p{task.endPage}
                          </span>
                          <span className="text-xs">{pageCount} pages</span>
                        </div>
                        <PriorityBadge priority={task.priority} />
                        <span
                          className={`text-xs px-2 py-1 rounded-md mt-1 ${
                            task.isDistributed
                              ? "bg-green-100 text-green-700"
                              : "bg-red-100 text-red-600"
                          }`}
                        >
                          {task.isDistributed ? "分配済み" : "未分配"}
                        </span>
                      </div>
                      <div className="flex flex-col items-end">
                        <div className="flex gap-1">
                          <Button
                            variant="ghost"
                            size="icon"
                            className="h-8 w-8"
                            onClick={() => handleEditWeeklyTask(task)}
                          >
                            <Pencil className="h-4 w-4" />
                          </Button>
                          <Button
                            variant="ghost"
                            size="icon"
                            className="h-8 w-8 text-destructive hover:text-destructive"
                            onClick={() => {
                              if (confirm("このタスクを削除しますか？")) {
                                handleDeleteWeeklyTask(task.id)
                              }
                            }}
                          >
                            <Trash2 className="h-4 w-4" />
                          </Button>
                          </div>
                          <Button size = "sm" className='mt-3'
                            onClick={() => {
                              setSelectedTask(task)
                              setShowAutoGenerateDialog(true)
                            }}
                          >
                            AutoGenerated
                          </Button>
                        </div>
                    </CardContent>
                  </Card>
                )
              })
            )}

            {/* Add Task Button */}
            <Button
              variant="outline"
              className="w-full border-dashed"
              onClick={() => setShowAddTaskDialog(true)}
            >
              <Plus className="mr-2 h-4 w-4" />
              Add Study Task
            </Button>
          </div>
        </div>
      
      {/* Add Task Dialog */}
      <Dialog open={showAddTaskDialog} onOpenChange={setShowAddTaskDialog}>
        <DialogContent className="max-w-[340px] rounded-xl">
          <DialogHeader>
            <DialogTitle>
              {editingTaskId ? 'Edit Study Task' : 'Add Study Task'}
            </DialogTitle>
          </DialogHeader>
          <div className="flex flex-col gap-4 py-4">
            <div className="flex flex-col gap-2">
              <Label>Subject</Label>
              <Select
                value={selectedSubject}
                onValueChange={setSelectedSubject}
              >
                <SelectTrigger>
                  <SelectValue placeholder="Select subject" />
                </SelectTrigger>

                <SelectContent>
                  <SelectItem value="all">All</SelectItem>
                  <SelectItem value="Mathematics">Mathematics</SelectItem>
                  <SelectItem value="English">English</SelectItem>
                  <SelectItem value="Japanese">Japanese</SelectItem>
                  <SelectItem value="Physics">Physics</SelectItem>
                  <SelectItem value="Chemistry">Chemistry</SelectItem>
                  <SelectItem value="Social">Social</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="flex flex-col gap-2">
              <Label>Select textbook</Label>
              <Select
                value={taskForm.bookId}
                onValueChange={(v) => setTaskForm((prev) => ({ ...prev, bookId: v }))}
              >
                <SelectTrigger>
                  <SelectValue placeholder="Choose a textbook" />
                </SelectTrigger>
                <SelectContent>
                  {filteredBooks.map((book) => (
                    <SelectItem key={book.id} value={book.id}>
                      {book.name}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div className="flex flex-col gap-2">
              <Label>Select priority</Label>
              <Select
                value={taskForm.priority}
                onValueChange={(v) => setTaskForm((prev) => ({ ...prev, priority: v }))}
              >
                <SelectTrigger>
                  <SelectValue placeholder="Choose a priority" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="high">High</SelectItem>
                  <SelectItem value="medium">Medium</SelectItem>
                  <SelectItem value="low">Low</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="grid grid-cols-2 gap-3">
              <div className="flex flex-col gap-2">
                <Label>Start page</Label>
                <Input
                  type="number"
                  value={taskForm.startPage}
                  onChange={(e) =>
                    setTaskForm((prev) => ({ ...prev, startPage: e.target.value }))
                  }
                  placeholder="30"
                />
              </div>
              <div className="flex flex-col gap-2">
                <Label>End page</Label>
                <Input
                  type="number"
                  value={taskForm.endPage}
                  onChange={(e) =>
                    setTaskForm((prev) => ({ ...prev, endPage: e.target.value }))
                  }
                  placeholder="60"
                />
              </div>
            </div>
          </div>
          <DialogFooter className="flex-row gap-2">
            <Button
              variant="outline"
              className="flex-1"
              onClick={() => {
                setShowAddTaskDialog(false)
                setTaskForm({ bookId: '', startPage: '', endPage: '', priority: '' })
                setEditingTaskId(null)
              }}
            >
              Cancel
            </Button>
            <Button
              className="flex-1"
              onClick={handleAddWeeklyTask}
              disabled={!taskForm.bookId || !taskForm.startPage || !taskForm.endPage || !taskForm.priority}
            >
              {editingTaskId ? 'Update' : 'Add'}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Auto Generate Dialog */}
      <Dialog open={showAutoGenerateDialog} onOpenChange={setShowAutoGenerateDialog}>
        <DialogContent>

          <DialogHeader>
            <DialogTitle>タスク分配</DialogTitle>
          </DialogHeader>

          <div className="space-y-3">
            {WEEKDAYS.map((day, index) => (
              <div key={day} className="flex items-center justify-between">
                <span className="w-16 font-medium">{day}</span>

                <div className="flex items-center gap-2">
                  {/* マイナスボタン */}
                  <Button
                    variant="outline"
                    size="icon"
                    className="h-8 w-8 rounded-full"
                    onClick={() => {
                      const newWeights = [...weights];
                      // 1減らす（0未満にしたくない場合は Math.max(0, weights[index] - 1)）
                      newWeights[index] = Math.max(0, weights[index] - 1);
                      setWeights(newWeights);
                    }}
                  >
                    <Minus className="h-4 w-4" />
                  </Button>

                  {/* 数値表示 */}
                  <div className="w-10 text-center font-mono text-lg">
                    {weights[index]}
                  </div>

                  {/* プラスボタン */}
                  <Button
                    variant="outline"
                    size="icon"
                    className="h-8 w-8 rounded-full"
                    onClick={() => {
                      const newWeights = [...weights];
                      // 1増やす
                      newWeights[index] = weights[index] + 1;
                      setWeights(newWeights);
                    }}
                  >
                    <Plus className="h-4 w-4" />
                  </Button>
                </div>
              </div>
            ))}
          </div>

          <Button
            className="mt-4 w-full"
            onClick={() => selectedTask && handleGenerateDailyTasks(selectedTask)}
          >
            生成
          </Button>

        </DialogContent>
      </Dialog>
    </div>
  )
}