'use client'

import { useState } from 'react'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Badge } from '@/components/ui/badge'
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from '@/components/ui/dialog'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { Label } from '@/components/ui/label'
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group'
import {
  Plus,
  Pencil,
  Trash2,
  Calendar,
  Star,
  ChevronLeft,
  ChevronRight,
  Sparkles,
} from 'lucide-react'
import type { WeeklyTask, StudyBook } from '@/lib/types'

interface PlanScreenProps {
  books: StudyBook[]
  weeklyTasks: WeeklyTask[]
  onAddWeeklyTask: (task: Omit<WeeklyTask, 'id'>) => void
  onUpdateWeeklyTask?: (taskId: string, updatedData: Partial<WeeklyTask>) => void
  onDeleteWeeklyTask?: (taskId: string) => void
  onGenerateDailyTasks?: (weekId: string, date: Date[], weights: number[]) => void
}

const POINTS_PER_PAGE = 5

export function PlanScreen({ books, weeklyTasks, onAddWeeklyTask, onUpdateWeeklyTask, onDeleteWeeklyTask, onGenerateDailyTasks }: PlanScreenProps) {
  // Weekly plan state
  const [currentWeek, setCurrentWeek] = useState(1)
  const [showAddTaskDialog, setShowAddTaskDialog] = useState(false)
  const [editingTaskId, setEditingTaskId] = useState<string | null>(null)
  const [taskForm, setTaskForm] = useState({
    bookId: '',
    startPage: '',
    endPage: '',
    priority: '',
  })
  const [showAutoGenerateDialog, setShowAutoGenerateDialog] = useState(false)

  // Calculate week dates
  const getWeekDates = (weekNum: number) => {
    const baseDate = new Date(2026, 2, 16) // Mar 16
    const start = new Date(baseDate)
    start.setDate(start.getDate() + (weekNum - 1) * 7)
    const end = new Date(start)
    end.setDate(end.getDate() + 6)
    const formatDate = (d: Date) => `${d.toLocaleDateString('en-US', { month: 'short' })} ${d.getDate()}`
    return `${formatDate(start)} - ${formatDate(end)}`
  }

  // Handlers for weekly plan
  const handleAddWeeklyTask = () => {
    if (!taskForm.bookId || !taskForm.startPage || !taskForm.endPage) return

    const startPage = Number(taskForm.startPage)
    const endPage = Number(taskForm.endPage)

    const selectedBook = books.find((b) => b.id === taskForm.bookId)

    const updates = {
      weekId: `week-${currentWeek}`,
      bookId: taskForm.bookId,
      bookName: selectedBook?.name ?? "",
      startPage,
      endPage,
      points: (endPage - startPage) * POINTS_PER_PAGE,
      priority: taskForm.priority,
  }

  if (editingTaskId) {
    onUpdateWeeklyTask?.(editingTaskId, updates)
  } else {
    onAddWeeklyTask?.(updates)
  }

  setShowAddTaskDialog(false)
  setTaskForm({ bookId: "", startPage: "", endPage: "" , priority: ""})
  setEditingTaskId(null)
}

  const handleEditWeeklyTask = (task: WeeklyTask) => {
  setTaskForm({
    bookId: task.bookId,
    startPage: task.startPage.toString(),
    endPage: task.endPage.toString(),
    priority: task.priority,
  })

  setEditingTaskId(task.id)
  setShowAddTaskDialog(true)
}

  const handleDeleteWeeklyTask = (taskId: string) => {
    onDeleteWeeklyTask?.(taskId)
  }

  const handleGenerateDailyTasks = () => {
    const baseDate = new Date(2026, 2, 16) // Mar 16
    const start = new Date(baseDate)
    start.setDate(start.getDate() + (currentWeek - 1) * 7)
    const end = new Date(start)
    end.setDate(end.getDate() + 6)
    onGenerateDailyTasks?.(`week-${currentWeek}`, [start,new Date(2026,2,18),new Date(2026,2,19), new Date(2026,2,20),new Date(2026,2,21),new Date(2026,2,22),end], [1, 1, 1, 1, 1, 0.5, 0.5])
    setShowAutoGenerateDialog(false)
  }

  const filteredTasks = weeklyTasks.filter((task) => task.weekId === `week-${currentWeek}`)

  function PriorityBadge({ priority }: { priority: string }) {
    if (priority === 'high') {
      return <Badge className="bg-red-100 text-red-700">High</Badge>
    }

    if (priority === 'medium') {
      return <Badge className="bg-yellow-100 text-yellow-700">Medium</Badge>
    }

    return <Badge className="bg-green-200 text-green-700">Low</Badge>
  }

  return (
    <div className="flex flex-col gap-4 pb-24">
      {/* Header */}
      <div className="flex flex-col gap-4">
        <h1 className="text-2xl font-bold text-foreground">Plan</h1>
      </div>

        <div className="flex flex-col gap-4">
          {/* Week Header */}
          <Card>
            <CardContent className="flex flex-col gap-3 p-4">
              <div className="flex items-center justify-between">
                <Button
                  variant="ghost"
                  size="icon"
                  className="h-8 w-8"
                  onClick={() => setCurrentWeek((w) => Math.max(1, w - 1))}
                >
                  <ChevronLeft className="h-5 w-5" />
                </Button>
                <div className="flex flex-col items-center">
                  <span className="text-lg font-semibold">Week {currentWeek}</span>
                  <span className="text-sm text-muted-foreground">
                    {getWeekDates(currentWeek)}
                  </span>
                </div>
                <Button
                  variant="ghost"
                  size="icon"
                  className="h-8 w-8"
                  onClick={() => setCurrentWeek((w) => w + 1)}
                >
                  <ChevronRight className="h-5 w-5" />
                </Button>
              </div>
            </CardContent>
          </Card>

          {/* Weekly Tasks */}
          <div className="flex flex-col gap-3">
            <h2 className="text-sm font-medium text-muted-foreground">Study Tasks</h2>
            {weeklyTasks.length === 0 ? (
              <Card>
                <CardContent className="py-8 text-center text-sm text-muted-foreground">
                  No tasks added yet
                </CardContent>
              </Card>
            ) : (
              filteredTasks.map((task) => {
                const pageCount = task.endPage - task.startPage + 1
                return (
                  <Card key={task.id}>
                    <CardContent className="flex items-center justify-between p-4">
                      <div className="flex flex-col gap-1">
                        <span className="font-medium text-foreground">
                          {task.bookName}
                        </span>
                        <div className="flex items-center gap-3 text-sm text-muted-foreground">
                          <span>
                            p{task.startPage} → p{task.endPage}
                          </span>
                          <span className="text-xs">{pageCount} pages</span>
                        </div>
                        <PriorityBadge priority={task.priority} />
                      </div>
                      <div className="flex gap-1">
                        <Button
                          variant="ghost"
                          size="icon"
                          className="h-8 w-8"
                          onClick={() => handleEditWeeklyTask(task)}
                        >
                          <Pencil className="h-4 w-4" />
                        </Button>
                        <Button
                          variant="ghost"
                          size="icon"
                          className="h-8 w-8 text-destructive hover:text-destructive"
                          onClick={() => {
                            if (confirm("このタスクを削除しますか？")) {
                              handleDeleteWeeklyTask(task.id)
                            }
                          }}
                        >
                          <Trash2 className="h-4 w-4" />
                        </Button>
                      </div>
                    </CardContent>
                  </Card>
                )
              })
            )}

            <Button
              variant="outline"
              className="w-full border-dashed"
              onClick={() => setShowAddTaskDialog(true)}
            >
              <Plus className="mr-2 h-4 w-4" />
              Add Study Task
            </Button>
          </div>

          {/* Auto Generate Button */}
          <Button
            className="w-full"
            size="lg"
            onClick={() => setShowAutoGenerateDialog(true)}
          >
            <Sparkles className="mr-2 h-4 w-4" />
            Auto Generate Daily Tasks
          </Button>
        </div>
      
      {/* Add Task Dialog */}
      <Dialog open={showAddTaskDialog} onOpenChange={setShowAddTaskDialog}>
        <DialogContent className="max-w-[340px] rounded-xl">
          <DialogHeader>
            <DialogTitle>
              {editingTaskId ? 'Edit Study Task' : 'Add Study Task'}
            </DialogTitle>
          </DialogHeader>
          <div className="flex flex-col gap-4 py-4">
            <div className="flex flex-col gap-2">
              <Label>Select textbook</Label>
              <Select
                value={taskForm.bookId}
                onValueChange={(v) => setTaskForm((prev) => ({ ...prev, bookId: v }))}
              >
                <SelectTrigger>
                  <SelectValue placeholder="Choose a textbook" />
                </SelectTrigger>
                <SelectContent>
                  {books.map((book) => (
                    <SelectItem key={book.id} value={book.id}>
                      {book.name}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div className="flex flex-col gap-2">
              <Label>Select priority</Label>
              <Select
                value={taskForm.priority}
                onValueChange={(v) => setTaskForm((prev) => ({ ...prev, priority: v }))}
              >
                <SelectTrigger>
                  <SelectValue placeholder="Choose a priority" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="high">High</SelectItem>
                  <SelectItem value="medium">Medium</SelectItem>
                  <SelectItem value="low">Low</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="grid grid-cols-2 gap-3">
              <div className="flex flex-col gap-2">
                <Label>Start page</Label>
                <Input
                  type="number"
                  value={taskForm.startPage}
                  onChange={(e) =>
                    setTaskForm((prev) => ({ ...prev, startPage: e.target.value }))
                  }
                  placeholder="30"
                />
              </div>
              <div className="flex flex-col gap-2">
                <Label>End page</Label>
                <Input
                  type="number"
                  value={taskForm.endPage}
                  onChange={(e) =>
                    setTaskForm((prev) => ({ ...prev, endPage: e.target.value }))
                  }
                  placeholder="60"
                />
              </div>
            </div>
            {taskForm.startPage && taskForm.endPage && (
              <div className="rounded-lg bg-muted p-3 text-center">
                <span className="text-sm text-muted-foreground">
                  {parseInt(taskForm.endPage) - parseInt(taskForm.startPage)} pages ={' '}
                </span>
                <span className="font-medium text-primary">
                  {(parseInt(taskForm.endPage) - parseInt(taskForm.startPage)) * POINTS_PER_PAGE} pts
                </span>
              </div>
            )}
          </div>
          <DialogFooter className="flex-row gap-2">
            <Button
              variant="outline"
              className="flex-1"
              onClick={() => {
                setShowAddTaskDialog(false)
                setTaskForm({ bookId: '', startPage: '', endPage: '', priority: '' })
                setEditingTaskId(null)
              }}
            >
              Cancel
            </Button>
            <Button
              className="flex-1"
              onClick={handleAddWeeklyTask}
              disabled={!taskForm.bookId || !taskForm.startPage || !taskForm.endPage || !taskForm.priority}
            >
              {editingTaskId ? 'Update' : 'Add'}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Auto Generate Dialog */}
      <Dialog open={showAutoGenerateDialog} onOpenChange={setShowAutoGenerateDialog}>
        <DialogContent className="max-w-[340px] rounded-xl">
          <DialogHeader>
            <DialogTitle>Generate Daily Tasks</DialogTitle>
          </DialogHeader>
          <div className="flex flex-col gap-4 py-4">

              <p className="text-sm text-muted-foreground">
                This will generate daily tasks based on your weekly plan.
              </p>
          </div>
          <DialogFooter className="flex-row gap-2">
            <Button
              variant="outline"
              className="flex-1"
              onClick={() => setShowAutoGenerateDialog(false)}
            >
              Cancel
            </Button>
            <Button
              className="flex-1"
              onClick={() => {
                handleGenerateDailyTasks()
              }}
            >
              Generate
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  )
}
